const weatherConditions = {
    0: "Clear",
    1: "LightCloud",
    2: "LightCloud",
    3: "HeavyCloud",
    45: "HeavyCloud",
    48: "HeavyCloud",
    51: "LightRain",
    53: "LightRain",
    55: "LightRain",
    56: "Sleet",
    57: "Sleet",
    61: "HeavyRain",
    63: "HeavyRain",
    65: "HeavyRain",
    66: "HeavyRain",
    67: "HeavyRain",
    71: "Snow",
    73: "Snow",
    75: "Snow",
    77: "Snow",
    80: "Shower",
    81: "Shower",
    82: "Shower",
    85: "Sleet",
    86: "Sleet",
    95: "Thunderstorm",
    96: "Thunderstorm",
    99: "Thunderstorm"
};
export default weatherConditions;